[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "package-manager-demo"
version = "1.0.1"
authors = [
  { name="Posit Software, PBC", email="rspm@posit.co" },
]
description = "A Demo Python Package"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/rstudio/package-manager-demo"
"Bug Tracker" = "https://github.com/rstudio/package-manager-demo/issues"

[tool.hatch.build.targets.wheel]
packages = ["src/package_manager_demo"]