job('builder-generator-py') {
    description('Posit Package Manager Python Build Job Generator')
    scm {
        git {
            remote {
                github('jvroberts/ppm-builder', 'ssh')
                branches('main')
                credentials('GIT_SSH_KEY')
            }
        }
    }
    triggers {
        scm('H/5 * * * *')
    }
    steps {
        dsl {
            text('''
folder('py-builders') {
    description('Python Package Builders')
}
def repos = streamFileFromWorkspace('py-repos.txt')
repos.eachLine { String repoUrl -> 
    def jobName = 'py-builders/' + repoUrl.substring(repoUrl.lastIndexOf('/') + 1)
    pipelineJob("${jobName}") {
        description('Autogenerated builder for ' + repoUrl)
        displayName(repoUrl)
        properties{
            githubProjectUrl(repoUrl)
        }
        definition {
            cps {
                script(readFileFromWorkspace('Jenkinsfile-py').replace('!!!REPO_URL!!!', repoUrl))
                sandbox()
            }
        }
    }
    if (!jenkins.model.Jenkins.instance.getItemByFullName("${jobName}")) {
    queue("${jobName}")
    }
}
'''
            )
        }
    }
}