job('builder-generator-r') {
    description('Posit Package Manager R Build Job Generator')
    scm {
        git {
            remote {
                github('jvroberts/ppm-builder', 'ssh')
                branches('main')
                credentials('GIT_SSH_KEY')
            }
        }
    }
    triggers {
        scm('H/5 * * * *')
    }
    steps {
        dsl {
            text('''
folder('r-builders') {
    description('R Package Builders')
}
def repos = streamFileFromWorkspace('r-repos.txt')
repos.eachLine { String repoUrl -> 
    def jobName = 'r-builders/' + repoUrl.substring(repoUrl.lastIndexOf('/') + 1)
    pipelineJob(jobName) {
        description('Autogenerated builder for ' + repoUrl)
        displayName(repoUrl)
        properties{
            githubProjectUrl(repoUrl)
        }
        definition {
            cps {
                script(readFileFromWorkspace('r-builder.groovy').replace('!!!REPO_URL!!!', repoUrl))
                sandbox()
            }
        }
    }
    if (!jenkins.model.Jenkins.instance.getItemByFullName(jobName)) {
    queue(jobName)
    }
}
'''
            )
        }
    }
}